# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('answer', models.CharField(max_length=500, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
