# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='\u041a\u0443\u0437\u044c\u043c\u0438\u043d \u0415\u0433\u043e\u0440 \u041a\u043e\u043d\u0441\u0442\u0430\u043d\u0442\u0438\u043d\u043e\u0432\u0438\u0447', max_length=128),
            preserve_default=False,
        ),
    ]
