# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('task_file', models.FileField(blank=True, upload_to=b'tasks/problems/')),
                ('individual', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, upload_to=b"tasks/solutions/<class 'django.contrib.auth.models.User'>")),
                ('mark', models.PositiveSmallIntegerField(blank=True)),
                ('assigned_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(to='user.Task')),
            ],
        ),
    ]
