# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160303_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task <built-in function id>',
            new_name='task_file',
        ),
    ]
