# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_auto_20160303_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to=b"tasks/solutions/<class 'django.contrib.auth.models.User'>")),
                ('mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='task',
            new_name='tasks',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='mark',
        ),
    ]
