# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_task_taskanswer_usertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
