# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20160303_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Task'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
